title: OnePolloWeb3学习知识库
description: 智能合约开发、链上交互和前端交互的学习资源
baseurl: "/OnePolloWeb3"
# baseurl: "/"
url: "https://ranxi2001.github.io"


# 构建设置
markdown: kramdown

sass:
  sass_dir: assets/css
  style: compressed